kind: PipelineRun
metadata:
  name: pipeline-release-please
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: release-please
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: create release
              image: quay.io/pabrahamsson/release-please:17.0.0-3
              workingDir: $(workspace.source.path)
              args:
                - github-release
                - --repo-url=pabrahamsson/rpmostree_exporter
                - --token=$GH_TOKEN
              env:
                - name: GH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
            - name: create release pr
              image: quay.io/pabrahamsson/release-please:17.0.0-3
              workingDir: $(workspace.source.path)
              args:
                - release-pr
                - --repo-url=pabrahamsson/rpmostree_exporter
                - --token=$GH_TOKEN
              env:
                - name: GH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: token
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
