---
name: pr
on:
  pull_request:
    paths:
      - "*/**"
      - .github/workflows/*.yml

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build project
        run: make && make clean
      - name: Run tests
        run: make gotest
