on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile

name: release-please
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build artifacts
        run: make
      - name: Create release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
      - name: Upload amd64 release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./bin/rpmostree-exporter_linux_amd64
      - name: Upload arm64 release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./bin/rpmostree-exporter_linux_arm64
