on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile

name: release-please
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_version: "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Create release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
      - name: Run Goreleaser
        if: ${{ build.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> 2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
