on:
  push:
    branches:
      - main
    paths-ignore:
      - Makefile

name: release-please
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Create release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
      - name: Wait for tag to be created
        run: sleep 5s
        shell: bash
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout2
      - name: Run Goreleaser
        if: ${{ steps.release.outputs.release_created }}
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> 2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
